In [ ]:
#Consider the below code to answer further questions:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [ ]:
type(array_list) is numpy. n dimentional array because array_list create a n-D array which use list_ as 
the objects 
list_ is a list of elements. 

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [13]:
list_ = [ '1' , 2.5 , '3' , '4' , 5]
array_list = np.array(object = list_)

print("Data types in list_:")
for i in list_:
    print(type(i))

print("\nData types in array_list:")
for i in array_list:
    print(type(i))


Data types in list_:
<class 'str'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'int'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [14]:
array_list = np.array(object = list_, dtype = int)
list_=[1,'sam',2.5,4,5,6]
for i in array_list:
    print(type(i))
for i in list_:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'int'>
<class 'str'>
<class 'float'>
<class 'int'>
<class 'int'>
<class 'int'>


In [ ]:
yes there will be the difference b/w the data type of eache lariable ,array_list and list_ because list_ is a 
collection of different data type while array_list is a n-D array. 

In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [16]:
num_array.shape

(2, 3)

In [17]:
num_array.size

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [24]:
def fun():
    zeros_array = np.zeros((3, 3))
    print(zeros_array)
fun()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
import numpy as np
identity_matrix = np.zeros((5, 5),int)
for i in range(5):
    identity_matrix[i, i] = 1

print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
